### ISSUE TITLE
Does not work with eDirectory 9.x

### ISSUE THREAD

**Issue by bristmi** [tjpatter/getpass#1]
ServerName:~ # /usr/local/sbin/getpass/getpass 192.168.1.1 cn=admin,o=novell password cn=bob,ou=users,o=novell
ldap_simple_bind_s: Can't contact LDAP server

Getting the "ldap_simple_bind_s" error when attempting to use getpass against an eDirectory 9.0 or 9.1 server. Is it possible to update the utility to work with the updated versions?

I suspect this is because eDirectory 9 moved away from ldap c to openldap.

**Comment by azuercher** [comment]
I have discovered same problem after upgrade to OES 2018.  Here is ldap trace from server:

10:43:37 89A72700 LDAP: New TLS connection 0x13e55b80 from 127.0.0.1:58394, monitor = 0x7bd97700, index = 32
10:43:37 7BD97700 LDAP: Monitor 0x7bd97700 initiating TLS handshake on connection 0x13e55b80
10:43:37 78BAE700 LDAP: DoTLSHandshake on connection 0x13e55b80
10:43:37 78BAE700 LDAP: TLS accept failure 1 on connection 0x13e55b80, setting err = -5875. Error stack:
   error:14076129:SSL routines:SSL23_GET_CLIENT_HELLO:only tls allowed in fips mode
10:43:37 78BAE700 LDAP: TLS handshake failed on connection 0x13e55b80, err = -5875
10:43:37 78BAE700 LDAP: Server closing connection 0x13e55b80, socket error = -5875
10:43:37 78BAE700 LDAP: Connection 0x13e55b80 closed

**Comment by azuercher** [comment]
I was able to make getpass to work with OES2018/edir 9 by following disabling FIPS from this doc:
https://www.netiq.com/documentation/edirectory-9/edir_install/data/b1gnto9x.html#

I ran the command "ndsconfig set n4u.server.fips_tls=0"

However it is probably a good idea to update getpass to support TLS and newer crypto.

**Comment by bristmi** [comment]
Nice find! Appreciate the info!

**Comment by lamczykz** [comment]
I'm here to confirm that getpass will not work with the newest versions of eDirectory. From what I can tell, getpass uses SSL and that was decommissioned by eDirectory as early as version 8.8.8. getpass would greatly benefit from being updated to use TLS. @tjpatter, is this something you'd be interested in doing?

**Comment by tjpatter** [comment]
I have just released an updated version that supports TLS, and is written in Python. Please find the code here: https://github.com/tjpatter/getpass3
